version: '3.1'
services:
  nodejs:
    build:
      context: images2build/nodejs
      args:
        - NODE_UID=${UID:-1000}
    ports:
      - "8081:8081"
      - "3000:3000"
    volumes:
       - "/home/vagrant/webapp:/home/node/www/"
    restart: always
    links:
      - db
      - mailhog
      - redis
  redis:
      image: redis:alpine
      restart: always
      ports:
        - 6379:6379
  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  monitoring:
    image: "portainer/portainer"
    ports:
       - "9000:9000"
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "/opt/portainer:/data"
    restart: always
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    restart: always
